version: '3.8'

services:
  stats-server:
    build:
      context: ./stat-service/stat-server
      dockerfile: Dockerfile
    image: java-explore-with-me/stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=statdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - ewm-network

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:16.1

networks:
  ewm-network:
    driver: bridge