CREATE TABLE IF NOT EXISTS users
(
    id    SERIAL PRIMARY KEY,
    email VARCHAR(256) UNIQUE,
    name  VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(64) UNIQUE
);
